- README.md
- templates/deployment.yaml
- templates/statefulset.yaml
- values.yaml
Adding lifecycle.preStop to not terminate the containers too early. For dind container it wait till there are no running docker containers. Wasn't sure if it was safe to terminate the launcher container before a job is finished.. so added a sleep to wait a little bit.
This prevents kubernetes from terminating the container while there is a running job.
Also added support for extra volume and volumeMount. Needed for mounting docker credentials.
> Add lifecycle and support for extra volumes

- templates/deployment.yaml
- templates/statefulset.yaml
- values.yaml
If the HPA is being used, replicas (in Deployment or StatefulSet) can't be used. 
That line needs to be removed in order for the HPA to work.
> Keep the replicas item for deployment and stateful sets as optional

- README.md
The chart works even if the underlying runtime used by Kubernetes is not Docker. Added a note to the docs to try to avoid this confusion.
> Explain that the chart still works with containerd

- .github/workflows/chart-publish-preprod.yml
- .github/workflows/chart-publish-prod.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Bump deprecated GH Action

- templates/deployment.yaml
`dockerd` doesn't handle PID1 responsibilities well.
Upstream issue:
https://github.com/docker-library/docker/issues/318
Blog description:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
Given that we aren't on the latest version of `dind`, and we don't use the native entry point wrapper, we should add this logic to ensure that process reaping occurs as expected.
Local testing:
https://gist.github.com/lexton/f7684b70ce7ca2f090490ded9ff1b9ad
> docker-init: handle linux init responsibilities

- templates/deployment.yaml
- templates/statefulset.yaml
- values.yaml
Same concept as in #17, fixed with #18 
Right now, there's no way to add additional `volumeMounts` to the `dind` container. 
A case in which this is useful is when a terraform configuration depends on modules stored in git rather than Spacelift. If additional SSL certs are required to connect to the git server, those could potentially be mounted in the worker/runner container with `SPACELIFT_WORKER_EXTRA_MOUNTS`, but while it's possible to define the environment variable there's no way to have the cert bundle mounted in the worker/runner if the bundle is not mounted in the host (`dind`) first
> Added support for `extraVolumeMounts` in the dind container

- .github/workflows/chart-publish-preprod.yml
We use a pre-release version number for the preprod builds, which prevents `helm pull` from finding them by default.
> Use `--devel` flag for helm pull test for preprod

- .github/workflows/chart-publish-preprod.yml
- .github/workflows/chart-publish-prod.yml
- Using the `--relative` flag to ensure that the chart URLs don't include the `s3://` protocol. This allows them to be downloaded via the https URL (https://downloads.spacelift.io/helm).
- Added a test to make sure that both charts can be pulled after publishing a new version.
> Use --relative flag on production chart push

- spacelift-worker-pool/templates/deployment.yaml
- spacelift-worker-pool/templates/statefulset.yaml
- spacelift-worker-pool/values.yaml
We use GCP for our Cloud provider and a few additional binaries/private-providers are needed inside our terraform runner container. We've pushed this built container (built ontop of the spacelift runner) to our GCP registry. Our deployment in Kubernetes is using [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to attach an existing service account from IAM to the pod itself.
I've attempted to follow [these docs](https://docs.spacelift.io/integrations/docker.html#customizing-the-runner-image) for our private worker pool that is init'd by this helm chart. I finally found the right combination where the `docker login`- config.json needs to be available inside the `launcher` container as well.
To accomplish this, I added a third container to the …
> feat: allow ability to add containers for things like gcp registry auth

- spacelift-worker-pool/values.yaml
It looks like the latest version of dind is causing issues in certain hosting environments. It may be due to this issue: https://github.com/docker-library/docker/issues/467.
Let's pin to a known-working version of `dind`.
> fix: pin DinD version to prevent iptables issue

- .github/workflows/chart-publish-prod.yml
The `helm package` command was missing the path to the chart.
> Fix publishing of workerpool controller chart

- spacelift-workerpool-controller/templates/deployment.yaml
- spacelift-workerpool-controller/values.yaml
Follow up of https://github.com/spacelift-io/kube-workerpool-controller/pull/93, but for the Helm chart.
I tested manually the output when metrics server is enabled and disabled.
We should work on adding basic golden files tests to catch formatting issues like the indent issue with `---` we had before.
> fix: fix kubelinter findings

- spacelift-workerpool-controller/templates/proxy-rbac.yaml
- spacelift-workerpool-controller/values.yaml
We were deploying the ClusterRole for kube-rbac-proxy even when the metrics server was not enabled. This doesn't make sense since the kube-rbac-proxy side-car container (and therefore the ClusterRole) are only used to implement authorization for accessing metrics.
> fix: don't deploy ClusterRole when metrics not enabled

- spacelift-workerpool-controller/Chart.yaml
- spacelift-workerpool-controller/values.yaml
This is to include [a fix](https://github.com/spacelift-io/kube-workerpool-controller/pull/119) on the worker pool controller that was causing the MQTT client to be disconnected.
> feat: bump Kubernetes controller to v0.0.11

- spacelift-workerpool-controller/templates/_helpers.tpl
Replace it with the default value `Helm` according to the doc https://helm.sh/docs/chart_template_guide/builtin_objects/
See action items in https://app.clickup.com/t/8694xkz2b for more context about this change.
> fix(CU-8694xkz2b): remove usage of `Release.Service`

- spacelift-workerpool-controller/Chart.yaml
- spacelift-workerpool-controller/values.yaml
This bumps the workerpool controller to `v0.0.12` to ship small improvements on error handling.
> feat: bump Kubernetes controller to v0.0.12

- spacelift-promex/README.md
The readme for installing the promex exporter is slightly incorrect. Config values are prefixed with spacelift.
> Fix spacelift-promex readme

- spacelift-promex/templates/deployment.yaml
Added a more secure/best practice security context to the promex container. It will allow customers to set the [Pod Security Policy to restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).
> feat: support a more secure security-context

- spacelift-workerpool-controller/Chart.yaml
- spacelift-workerpool-controller/crds/workerpool-crd.yaml
- spacelift-workerpool-controller/values.yaml
We've added a new `spec.pod.customBinariesPath` option to the WorkerPool resource that allows custom paths to be injected at the start of the path for workers.
> feat: add support for customBinariesPath to k8s controller

- spacelift-workerpool-controller/Chart.yaml
- spacelift-workerpool-controller/templates/_helpers.tpl
- spacelift-workerpool-controller/templates/deployment.yaml
- spacelift-workerpool-controller/templates/leader-election-rbac.yaml
- spacelift-workerpool-controller/templates/manager-rbac.yaml
- spacelift-workerpool-controller/templates/metrics-rbac.yaml
- spacelift-workerpool-controller/templates/serviceaccount.yaml
- spacelift-workerpool-controller/values.yaml
This PR adds some extra templating options to the `spacelift-workerpool-controller` chart
- Allow using an existing service account instead of always creating on, as well as allow customising the name of the service account created  
- **This is a no-op if the default values are not modified**. It keeps the previous behaviour as default and should not trigger a change in the service account name of current users of the chart.
- Allow adding extra labels to both the deployment and the pods
- Allow adding annotations to the controller manager deployment
- Allow adding volumes and volumeMounts to controller manager
Please let me know if this does not conform to some of your style agreements, or if you would prefer the service account changes in a separated PR.
> Add more fields to template

- spacelift-workerpool-controller/Chart.yaml
- spacelift-workerpool-controller/templates/deployment.yaml
- spacelift-workerpool-controller/values.yaml
Adds `imagePullSecrets` option to the `spacelift-workerpool-controller` chart to support pulling the mirrored image from the private registries.
> Support image pull secrets in workerpool controller

- .github/workflows/build-chart.yml
- .github/workflows/chart-publish-preprod.yml
- .github/workflows/chart-publish-prod.yml
- spacelift-self-hosted/.helmignore
- spacelift-self-hosted/Chart.yaml
- spacelift-self-hosted/README.md
- spacelift-self-hosted/templates/NOTES.txt
- spacelift-self-hosted/templates/_helpers.tpl
- spacelift-self-hosted/templates/drain-deployment.yaml
- spacelift-self-hosted/templates/drain-serviceaccount.yaml
- spacelift-self-hosted/templates/ingress-v6.yaml
- spacelift-self-hosted/templates/ingress.yaml
- spacelift-self-hosted/templates/mqtt-service.yaml
- spacelift-self-hosted/templates/scheduler-deployment.yaml
- spacelift-self-hosted/templates/scheduler-serviceaccount.yaml
- spacelift-self-hosted/templates/server-deployment.yaml
- spacelift-self-hosted/templates/server-serviceaccount.yaml
- spacelift-self-hosted/templates/service.yaml
- spacelift-self-hosted/templates/serviceaccount.yaml
- spacelift-self-hosted/values.yaml
This is just a copy and paste of the chart that is currently in our self-hosted repository. No changes.
I just added a readme with a link to the docs, and I'll update it once our doc is fully merged with mainstream.
Once the chart is deployed, I'll also update the docs.
> feat: add self-hosted chart

- spacelift-self-hosted/templates/mqtt-service.yaml
- spacelift-self-hosted/templates/service.yaml
- spacelift-self-hosted/values.yaml
My previous change ended up breaking the Ingress definitions because I hadn't updated them to reference the new service name. Instead I'm taking a simpler approach of just setting the `fullnameOverride` to `spacelift` by default. This will have the same effect of being backwards compatible with our existing installations, but is a little simpler.
> fix: set fullnameOverride by default for self-hosted chart

- spacelift-workerpool-controller/Chart.yaml
Bump promex chart version in workerpool controller to contain all recent changes
Connected with #106
> chore: Bump promex version in workerpool-controller
