spacelift-io/spacelift-helm-charts

templates/deployment.yaml, templates/statefulset.yaml, values.yaml
Add podLabels and extraLabels into the Helm template. The first let's you set the Deployment labels, the second the pod labels.
=> Add podLabels and extraLabels to the helm template.

templates/deployment.yaml, templates/statefulset.yaml, values.yaml
=> Added support for `extraEnv` in the dind container

.github/workflows/build-chart.yml, .github/workflows/chart-publish-preprod.yml, .github/workflows/chart-publish-prod.yml
=> Bump GH Action versions

.github/workflows/build-chart.yml, .github/workflows/chart-publish-preprod.yml, .github/workflows/chart-publish-prod.yml, spacelift-workerpool-controller/.helmignore, spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/README.md, spacelift-workerpool-controller/crds/worker-crd.yaml, spacelift-workerpool-controller/crds/workerpool-crd.yaml, spacelift-workerpool-controller/templates/_helpers.tpl, spacelift-workerpool-controller/templates/deployment.yaml, spacelift-workerpool-controller/templates/leader-election-rbac.yaml, spacelift-workerpool-controller/templates/manager-rbac.yaml, spacelift-workerpool-controller/templates/metrics-reader-rbac.yaml, spacelift-workerpool-controller/templates/metrics-service.yaml, spacelift-workerpool-controller/templates/proxy-rbac.yaml, spacelift-workerpool-controller/templates/serviceaccount.yaml, spacelift-workerpool-controller/values.yaml
I copy pasted the chart from the controller repo, updated the GH workflows and add a `README.md` in the chart folder.
=> feat(CU-86931r7wm): add workerpool controller helm chart

spacelift-workerpool-controller/templates/deployment.yaml, spacelift-workerpool-controller/templates/manager-rbac.yaml, spacelift-workerpool-controller/values.yaml
=> feat: allow to deploy without a `ClusterRole`

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/crds/workerpool-crd.yaml, spacelift-workerpool-controller/values.yaml
Adding support for:
- Automatically cleaning up successful Pods.
- Overriding the launcher image.
=> feat: update workerpool controller to v0.0.1-alpha4

spacelift-workerpool-controller/templates/manager-rbac.yaml
=> fix: whitespace trailing prevents role deployment

spacelift-workerpool-controller/crds/worker-crd.yaml, spacelift-workerpool-controller/crds/workerpool-crd.yaml
Just a no-op indent fix, but will make the next updates more easy 😅
=> chore: fix indent of controller CRDs

spacelift-workerpool-controller/Chart.yaml
Forgot to also bump the chart metadata file
=> feat: update controller app version

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/values.yaml
Updating the Helm chart to use the new v0.0.2 release.
=> feat: bump Kubernetes controller to v0.0.2

spacelift-operator/Chart.yaml
=> fix: spacelift operator chart name

.github/workflows/build-chart.yml, .github/workflows/chart-publish-preprod.yml, .github/workflows/chart-publish-prod.yml, spacelift-workerpool-controller/Chart.yaml
=> feat: make spacelift-promex a dependency of this chart conditionally

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/crds/workerpool-crd.yaml, spacelift-workerpool-controller/values.yaml
=> feat: bump Kubernetes controller to v0.0.13

spacelift-promex/Chart.yaml, spacelift-promex/templates/deployment.yaml, spacelift-promex/values.yaml
=> add pod annotations to promex

spacelift-workerpool-controller/Chart.yaml
Bump the spacelift-promex dependency in the spacelift-workerpool-controller chart
=> feat: bump spacelift-promex dependency

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/templates/serviceaccount.yaml, spacelift-workerpool-controller/values.yaml, vcs-agent/Chart.yaml, vcs-agent/templates/serviceaccount.yaml, vcs-agent/values.yaml
Support Additiona Labels in `vcs-agent` & `spacelift-workerpool-controller` service accounts.
=> Service accounts additional labels

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/values.yaml
=> feat: bump controller version to v0.0.14

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/crds/workerpool-crd.yaml, spacelift-workerpool-controller/values.yaml
=> feat: update workerpool controller

spacelift-self-hosted/Chart.yaml
=> fix: self hosted chart name mistake

.github/workflows/build-chart.yml, .github/workflows/chart-publish-preprod.yml, .github/workflows/chart-publish-prod.yml
=> chore: bump helm version

spacelift-self-hosted/Chart.yaml
=> feat: bump self-hosted chart version

spacelift-flows-agent/templates/deployment.yaml
=> fix: quote agent pool size

spacelift-workerpool-controller/Chart.yaml, spacelift-workerpool-controller/templates/servicemonitor.yaml, spacelift-workerpool-controller/values.yaml
=> feat: Add servicemonitor for spacelift-workerpool-controller
